In [13]:
import pickle
import pandas as pd
import re

In [2]:
ls

Data_Scraping_Prototype.ipynb  cleaning_prototype.ipynb
README.md                      movie_info.pickle
Untitled.ipynb                 movie_stubs.pickle

In [7]:
#load movie stub and info pickles
movie_info = pickle.load(open('movie_info.pickle', 'rb'))
movie_stubs = pickle.load(open('movie_stubs.pickle', 'rb'))

In [15]:
movie_info = pd.DataFrame(movie_info)
movie_info.set_index('title', inplace=True)

KeyError: "None of ['title'] are in the columns"

In [16]:
movie_info.head()

,desc,distr,opening,budget,mpaa,runtime,genres,gross_dom,gross_inter,gross_world
title,,,,,,,,,,
Avengers: Endgame,After the devastating events of Avengers: Infi...,Walt Disney Studios Motion PicturesSee full co...,"$357,115,0074,662\n theaters","$356,000,000",PG-13,3 hr 1 min,"Action, Adventure, Drama, Sci-Fi","$858,373,000","$1,939,427,564","$2,797,800,564"
The Lion King,"After the murder of his father, a young lion p...",Walt Disney Studios Motion PicturesSee full co...,"$191,770,7594,725\n theaters","$260,000,000",PG,1 hr 58 min,"Adventure, Animation, Drama, Family, Musical","$543,638,043","$1,113,305,351","$1,656,943,394"
Toy Story 4,"When a new toy called ""Forky"" joins Woody and ...",Walt Disney Studios Motion PicturesSee full co...,"$120,908,0654,575\n theaters","$200,000,000",G,1 hr 40 min,"Adventure, Animation, Comedy, Family, Fantasy","$434,038,008","$639,356,585","$1,073,394,593"
Frozen II,"Anna, Elsa, Kristoff, Olaf and Sven leave Aren...",Walt Disney Studios Motion PicturesSee full co...,"$130,263,3584,440\n theaters","$150,000,000",PG,1 hr 43 min,"Adventure, Animation, Comedy, Family, Fantasy,...","$477,373,578","$972,653,355","$1,450,026,933"
Captain Marvel,Carol Danvers becomes one of the universe's mo...,Walt Disney Studios Motion PicturesSee full co...,"$153,433,4234,310\n theaters","$160,000,000",PG-13,2 hr 3 min,"Action, Adventure, Sci-Fi","$426,829,839","$701,444,955","$1,128,274,794"

In [9]:
movie_stubs.head()

,link_stub,release,theaters
Avengers: Endgame,/release/rl3059975681/?ref_=bo_yld_table_1,"Apr 26, 2019",4662
The Lion King,/release/rl3321923073/?ref_=bo_yld_table_2,"Jul 19, 2019",4802
Toy Story 4,/release/rl3798500865/?ref_=bo_yld_table_3,"Jun 21, 2019",4575
Frozen II,/release/rl2424210945/?ref_=bo_yld_table_4,"Nov 22, 2019",4440
Captain Marvel,/release/rl3009644033/?ref_=bo_yld_table_5,"Mar 8, 2019",4310

In [23]:
movie_df = movie_stubs.merge(movie_info, left_index=True, right_index=True)

movie_df.drop_duplicates(inplace=True)

In [29]:
#quick check to see if I have enough budget data
movie_df.budget.isnull().value_counts()

False    2988
True     1207
Name: budget, dtype: int64

In [90]:
#removing trailing number of theaters from opening column

def clean_openings(opening):
    """
    Opening String grabbed both money and the row below.
    $357,115,0074,662\n theaters
    uses regex to remove opening theaters and the string
    input: (str)
    return : (str) $###,###,###
    """
    try:
        return re.search('^[$][0-9]{1,3},[0-9]{3},[0-9]{3}', opening).group()
    except:
        return None
    
movie_df['opening'] = movie_df.opening.map(clean_openings)

In [94]:
movie_df.filter(regex='Avengers', axis=0)

,link_stub,release,theaters,desc,distr,opening,budget,mpaa,runtime,genres,gross_dom,gross_inter,gross_world
Avengers: Age of Ultron,/release/rl675644929/?ref_=bo_yld_table_3,"May 1, 2015",4276,When Tony Stark and Bruce Banner try to jump-s...,Walt Disney Studios Motion PicturesSee full co...,"$191,271,109","$250,000,000",PG-13,2 hr 21 min,"Action, Adventure, Sci-Fi","$459,005,868","$943,800,000","$1,402,805,868"
Avengers: Endgame,/release/rl3059975681/?ref_=bo_yld_table_1,"Apr 26, 2019",4662,After the devastating events of Avengers: Infi...,Walt Disney Studios Motion PicturesSee full co...,"$357,115,007","$356,000,000",PG-13,3 hr 1 min,"Action, Adventure, Drama, Sci-Fi","$858,373,000","$1,939,427,564","$2,797,800,564"
Avengers: Infinity War,/release/rl3043198465/?ref_=bo_yld_table_2,"Apr 27, 2018",4474,The Avengers and their allies must be willing ...,Walt Disney Studios Motion PicturesSee full co...,"$257,698,183",None,PG-13,2 hr 29 min,"Action, Adventure, Sci-Fi","$678,815,482","$1,369,544,272","$2,048,359,754"
The Avengers,/release/rl709199361/?ref_=bo_yld_table_1,"May 4, 2012",4349,Earth's mightiest heroes must come together an...,Walt Disney Studios Motion PicturesSee full co...,"$207,438,708","$220,000,000",PG-13,2 hr 23 min,"Action, Adventure, Sci-Fi","$623,357,910","$895,455,078","$1,518,812,988"

In [113]:
def clean_money(money):
    """
    Convert Money from string to number. 
    
    input : (str) 
    return : (int)
    """
    try:
        return ''.join(money.split(','))[1:]
    except:
        return None

In [116]:
movie_df.opening = movie_df.opening.map(clean_money)
movie_df.budget = movie_df.budget.map(clean_money)
movie_df.gross_dom = movie_df.gross_dom.map(clean_money)
movie_df.gross_inter = movie_df.gross_inter.map(clean_money)
movie_df.gross_world = movie_df.gross_world.map(clean_money)

In [117]:
movie_df.head()

,link_stub,release,theaters,desc,distr,opening,budget,mpaa,runtime,genres,gross_dom,gross_inter,gross_world
10 Cloverfield Lane,/release/rl1329956353/?ref_=bo_yld_table_44,"Mar 11, 2016",3427,"After getting in a car accident, a woman is he...",Paramount PicturesSee full company information...,24727437,None,PG-13,1 hr 43 min,"Action, Drama, Horror, Mystery, Sci-Fi, Thriller",72082998,38134000,110216998
"10,000 BC",/release/rl977372673/?ref_=bo_yld_table_26,"Mar 7, 2008",3454,"In the prehistoric past, D'Leh is a mammoth hu...",Warner Bros.See full company information\n\n,35867488,105000000,PG-13,1 hr 49 min,"Action, Adventure, Drama, Fantasy, History",94784201,175000000,269784201
102 Dalmatians,/release/rl927041025/?ref_=bo_yld_table_137,"Nov 22, 2001",2704,Cruella DeVil gets out of prison and goes afte...,Walt Disney Studios Motion PicturesSee full co...,19883351,85000000,None,1 hr 40 min,"Adventure, Comedy, Family",66957026,116654745,183611771
102 Dalmatians,/release/rl927041025/?ref_=bo_yld_table_44,"Nov 22, 2000",2704,Cruella DeVil gets out of prison and goes afte...,Walt Disney Studios Motion PicturesSee full co...,19883351,85000000,None,1 hr 40 min,"Adventure, Comedy, Family",66957026,116654745,183611771
12 Rounds,/release/rl440501761/?ref_=bo_yld_table_147,"Mar 27, 2009",2331,Detective Danny Fisher discovers his girlfrien...,Twentieth Century FoxSee full company informat...,5329240,None,PG-13,1 hr 48 min,"Action, Crime, Thriller",12234694,5045632,17280326

In [120]:
with open('clean_movie_df.pickle', 'wb') as to_write:
    pickle.dump(movie_df, to_write)

In [119]:
ls

Data_Scraping_Prototype.ipynb  cleaning_prototype.ipynb
README.md                      movie_info.pickle
Untitled.ipynb                 movie_stubs.pickle
clean_movie_df.pickle

September 30, 2020

In [2]:
movie_df.head()

,link_stub,release,theaters,desc,distr,opening,budget,mpaa,runtime,genres,gross_dom,gross_inter,gross_world
10 Cloverfield Lane,/release/rl1329956353/?ref_=bo_yld_table_44,"Mar 11, 2016",3427,"After getting in a car accident, a woman is he...",Paramount PicturesSee full company information...,24727437,None,PG-13,1 hr 43 min,"Action, Drama, Horror, Mystery, Sci-Fi, Thriller",72082998,38134000,110216998
"10,000 BC",/release/rl977372673/?ref_=bo_yld_table_26,"Mar 7, 2008",3454,"In the prehistoric past, D'Leh is a mammoth hu...",Warner Bros.See full company information\n\n,35867488,105000000,PG-13,1 hr 49 min,"Action, Adventure, Drama, Fantasy, History",94784201,175000000,269784201
102 Dalmatians,/release/rl927041025/?ref_=bo_yld_table_137,"Nov 22, 2001",2704,Cruella DeVil gets out of prison and goes afte...,Walt Disney Studios Motion PicturesSee full co...,19883351,85000000,None,1 hr 40 min,"Adventure, Comedy, Family",66957026,116654745,183611771
102 Dalmatians,/release/rl927041025/?ref_=bo_yld_table_44,"Nov 22, 2000",2704,Cruella DeVil gets out of prison and goes afte...,Walt Disney Studios Motion PicturesSee full co...,19883351,85000000,None,1 hr 40 min,"Adventure, Comedy, Family",66957026,116654745,183611771
12 Rounds,/release/rl440501761/?ref_=bo_yld_table_147,"Mar 27, 2009",2331,Detective Danny Fisher discovers his girlfrien...,Twentieth Century FoxSee full company informat...,5329240,None,PG-13,1 hr 48 min,"Action, Crime, Thriller",12234694,5045632,17280326

In [15]:
#Remove noise from distributor column
def clean_distr(x):
    try:
        return x[:re.search('See full company', x).start()]
    except:
        return None

movie_df.distr = movie_df.distr.apply(clean_distr)

In [35]:
#convert runtime to numbers of mins 
def runtime_mins(runt):
    """
    Converts runtime to total minutes 
    args:
    runt (str) : 1 hr 43 min
    return:
    n (int) : number of minutes
    """
    n = 0
    try:
        if runt == '2 hr':
            return 120
        elif runt == '45 min':
            return 45
        elif runt == '1 hr':
            return 60
        elif runt == '48 min':
            return 48
        elif runt == '3 hr':
            return 180
        elif runt == '30 min':
            return 30
        
        hr, mins = int(runt.split()[0]), int(runt.split()[2])
        n = hr*60+mins

    except:
        return None
    
    return n

movie_df.runtime = movie_df.runtime.apply(runtime_mins)

In [55]:
with open('clean_movie_df.pickle', 'wb') as to_write:
    pickle.dump(movie_df, to_write)

In [56]:
movie_df = pickle.load(open('clean_movie_df.pickle', 'rb'))

In [27]:
movie_df.runtime.isnull().value_counts()

False    4191
True        4
Name: runtime, dtype: int64

In [53]:
movie_df.isnull().sum()

link_stub      0
release        0
theaters       0
desc           0
distr          0
opening        0
budget         0
mpaa           0
runtime        0
genres         0
gross_dom      0
gross_inter    0
gross_world    0
dtype: int64

In [52]:
movie_df.dropna(axis=0, inplace=True)

In [57]:
movie_df

,link_stub,release,theaters,desc,distr,opening,budget,mpaa,runtime,genres,gross_dom,gross_inter,gross_world
"10,000 BC",/release/rl977372673/?ref_=bo_yld_table_26,"Mar 7, 2008",3454,"In the prehistoric past, D'Leh is a mammoth hu...",Warner Bros.,35867488,105000000,PG-13,109.0,"Action, Adventure, Drama, Fantasy, History",94784201,175000000,269784201
13 Going on 30,/release/rl524387841/?ref_=bo_yld_table_57,"Apr 23, 2004",3453,A girl makes a wish on her thirteenth birthday...,Revolution Studios,21054283,37000000,PG-13,98.0,"Comedy, Fantasy, Romance",57231747,39223950,96455697
13 Hours,/release/rl2105378305/?ref_=bo_yld_table_62,"Jan 15, 2016",2917,"During an attack on a U.S. compound in Libya, ...",Paramount Pictures,16194738,50000000,R,144.0,"Action, Drama, History, War",52853219,16558151,69411370
15 Minutes,/release/rl188843521/?ref_=bo_yld_table_92,"Mar 9, 2001",2337,A homicide detective and a fire marshal must s...,New Line Cinema,10523154,60000000,R,120.0,"Action, Crime, Drama, Thriller",24403552,31956428,56359980
2 Fast 2 Furious,/release/rl1178699265/?ref_=bo_yld_table_15,"Jun 6, 2003",3418,Former cop Brian O'Conner is called upon to bu...,Universal Pictures,50472480,76000000,PG-13,107.0,"Action, Crime, Thriller",127154901,109195760,236350661
...,...,...,...,...,...,...,...,...,...,...,...,...,...
xXx,/release/rl1450870273/?ref_=bo_yld_table_481,"Aug 9, 2003",3536,"An extreme sports athlete, Xander Cage, is rec...",Revolution Studios,44506103,70000000,PG-13,124.0,"Action, Adventure, Thriller",142109382,135339000,277448382
xXx,/release/rl1450870273/?ref_=bo_yld_table_15,"Aug 9, 2002",3536,"An extreme sports athlete, Xander Cage, is rec...",Revolution Studios,44506103,70000000,PG-13,124.0,"Action, Adventure, Thriller",142109382,135339000,277448382
xXx: Return of Xander Cage,/release/rl1904182785/?ref_=bo_yld_table_63,"Jan 20, 2017",3651,Xander Cage is left for dead after an incident...,Paramount Pictures,20130142,85000000,PG-13,107.0,"Action, Adventure, Thriller",44898413,301219864,346118277
Æon Flux,/release/rl1212188161/?ref_=bo_yld_table_270,"Dec 2, 2006",2608,Aeon Flux is a mysterious assassin working for...,Paramount Pictures,12661112,62000000,PG-13,93.0,"Action, Adventure, Sci-Fi, Thriller",25874337,27447336,53321673
Æon Flux,/release/rl1212188161/?ref_=bo_yld_table_102,"Dec 2, 2005",2608,Aeon Flux is a mysterious assassin working for...,Paramount Pictures,12661112,62000000,PG-13,93.0,"Action, Adventure, Sci-Fi, Thriller",25874337,27447336,53321673

In [59]:
crew_list = pickle.load(open('cast_info.pickle', 'rb'))

In [63]:
crew_df.drop(columns=['Nov 9, 2001', 'Oct 9, 2015'], inplace=True)

In [86]:
crew_list = pickle.load(open('cast_info.pickle', 'rb'))
crew_df = pd.DataFrame(crew_list)

crew_df.drop(columns=['Nov 9, 2001', 'Oct 9, 2015'], inplace=True)
crew_df.title = crew_df.title.apply(lambda x : x[:re.search('[(][0-9]{4}[)]', x).start()].rstrip())
crew_df.set_index('title', inplace=True)

In [91]:
movie_df = movie_df.merge(crew_df, left_index=True, right_index=True)

In [93]:
ls

Data_Scraping_Prototype.ipynb           clean_movie_df.pickle
Data_Scraping_Prototype_Selenium.ipynb  cleaning_prototype.ipynb
Feature Engineering.ipynb               geckodriver.log
README.md                               movie_info.pickle
cast_info.pickle                        movie_stubs.pickle
cast_info_list1500_to_end.pickle        processed_movie_df.pickle
cast_info_list_start_to_1500.pickle     usholidays.csv

In [94]:
with open('clean_movie_df.pickle', 'wb') as to_write:
    pickle.dump(movie_df, to_write)